# Generated by Django 5.2.7 on 2025-10-26 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Usado em'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL, verbose_name='Usado por'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Uso único (1).', verbose_name='Máximo de usos'),
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_until', models.DateTimeField(blank=True, null=True, verbose_name='Suspenso até')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo do bloqueio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_status', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Status de Conta',
                'verbose_name_plural': 'Status de Contas',
            },
        ),
    ]
