# Generated by Django 5.2.7 on 2025-10-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='proprietario_cpf',
            field=models.CharField(max_length=14, verbose_name='CPF/CNPJ'),
        ),
    ]
